# Generated by Django 2.2.6 on 2019-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPE_name', models.TextField()),
                ('CVE_name', models.TextField()),
            ],
        ),
    ]
