# Generated by Django 2.2.6 on 2019-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPEC_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAPEC_name', models.TextField()),
                ('CAPEC_description', models.TextField()),
                ('CAPEC_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CVE_name', models.TextField()),
                ('Date1', models.TextField()),
                ('Description', models.TextField()),
                ('CVSS_name', models.TextField()),
                ('CVSS_description', models.TextField()),
                ('CWE_name', models.TextField()),
                ('Hyperlink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CWE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CWE_name', models.TextField()),
                ('CAPEC_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CWE_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CWE_name', models.TextField()),
                ('CWE_description', models.TextField()),
                ('CWE_link', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cpe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
