# Generated by Django 2.2.6 on 2019-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191107_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPE_distinct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('CPE_name', models.TextField()),
            ],
        ),
    ]
