# Generated by Django 2.2.7 on 2019-12-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cpe_distinct'),
    ]

    operations = [
        migrations.AddField(
            model_name='capec_description',
            name='ATT_CK_link',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='capec_description',
            name='ATT_CK_name',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='capec_description',
            name='id_ATT_CK',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='capec_description',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cve',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cwe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cwe_description',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
