# Generated by Django 2.2.6 on 2019-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191220_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='att_ck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_att_ck', models.TextField()),
                ('name_att_ck', models.TextField()),
                ('description_att_ck', models.TextField()),
                ('tactic', models.TextField()),
                ('platform', models.TextField()),
                ('permissions_required', models.TextField()),
                ('effective_permissions', models.TextField()),
                ('data_sources', models.TextField()),
                ('defense_bypassed', models.TextField()),
                ('version', models.TextField()),
            ],
        ),
    ]
