# Generated by Django 2.2.6 on 2020-01-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cwe_distinct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPEC_distinct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('CAPEC_name', models.TextField()),
                ('CAPEC_description', models.TextField()),
            ],
        ),
    ]
