from django.urls import path
from django.conf.urls import url
from . import views

#cpe_name = 'cpe:2\.3:[aho](?::(?:[a-zA-Z0-9!"#$%&' + "()*+,\\\-_.\/;<=>?@\[\]^`{|}~]|\\:)+){10}$"
urlpatterns = [
    #url(r'^'),
    url(r"^cpe/views_cves/.*$", views.views_cve),
    url(r'^cpe/$', views.index),
    url(r"^cpe/views_cve/cve_of_cpe_/CVE-\d+-\d+$", views.about_cve),
    url(r"^cpe/views_cve/cve_of_cpe_/CVE-\d+-\d+/CWE-\d+$", views.about_cwe),
    url(r"^cpe/views_cve/cve_of_cpe_/CVE-\d+-\d+/CWE-\d+/CAPEC-\d+$", views.about_capec),
    url(r"^cpe/views_cve/cve_of_cpe_/CVE-\d+-\d+/CWE-\d+/CAPEC-\d+/T\d+$", views.att_ck),
    url(r"^cve/$", views.cve),
    url(r"^cve/CVE-\d+-\d+$", views.cve_info),
    url(r"^cve/CVE-\d+-\d+/CWE-\d+$", views.about_cwe),
    url(r"^cve/CVE-\d+-\d+/CWE-\d+/CAPEC-\d+$", views.about_capec),
    url(r"^cve/CVE-\d+-\d+/CWE-\d+/CAPEC-\d+/T\d+$", views.att_ck),
    url(r"^search_cve/$", views.search, name='search_cve'),
    url(r"^search_cve/CVE-\d+-\d+$", views.cve_info),
    url(r"^search_cve/CVE-\d+-\d+/CWE-\d+$", views.about_cwe),
    url(r"^search_cve/CVE-\d+-\d+/CWE-\d+/CAPEC-\d+$", views.about_capec),
    url(r"^search_cve/CVE-\d+-\d+/CWE-\d+/CAPEC-\d+/T\d+$", views.att_ck),
    url(r"^search_cpe/$", views.search_cpe, name='search_cpe'),
    url(r"^search_cpe/views_cves/.*$", views.views_cve),
    url(r"^search_cpe/views_cve/cve_of_cpe_/CVE-\d+-\d+$", views.about_cve),
    url(r"^search_cpe/views_cve/cve_of_cpe_/CVE-\d+-\d+/CWE-\d+$", views.about_cwe),
    url(r"^search_cpe/views_cve/cve_of_cpe_/CVE-\d+-\d+/CWE-\d+/CAPEC-\d+$", views.about_capec),
    url(r"^search_cpe/views_cve/cve_of_cpe_/CVE-\d+-\d+/CWE-\d+/CAPEC-\d+/T\d+$", views.att_ck),
    url(r"^cwe/$", views.cwe),
    url(r"^cwe/CWE-\d+$", views.about_cwe),
    url(r"^cwe/CWE-\d+/CAPEC-\d+$", views.about_capec),
    url(r"^cwe/CWE-\d+/CAPEC-\d+/T\d+$", views.att_ck),
    url(r"^search_cwe/$", views.search_cwe, name='search_cwe'),
    url(r"^search_cwe/CWE-\d+$", views.about_cwe),
    url(r"^search_cwe/CWE-\d+/CAPEC-\d+$", views.about_capec),
    url(r"^search_cwe/CWE-\d+/CAPEC-\d+/T\d+$", views.att_ck),
    url(r"^capec/$", views.capec),
    url(r"^capec/CAPEC-\d+$", views.about_capec),
    url(r"^capec/CAPEC-\d+/T\d+$", views.att_ck),
    url(r"^search_capec/$", views.search_capec, name='search_capec'),
    url(r"^search_capec/CAPEC-\d+$", views.about_capec),
    url(r"^search_capec/CAPEC-\d+/T\d+$", views.att_ck),
    url(r"^att_ck_all/$", views.att_ck_all),
    url(r"^att_ck_all/T\d+$", views.att_ck),
    url(r"^search_att_ck_all/$", views.search_att_ck_all, name='search_att_ck_all'),
    url(r"^search_att_ck_all/T\d+$", views.att_ck),
    url(r"^infograf/$", views.infograf, name='refresh'),
    url(r"^cpes_CVE-\d+-\d+/$", views.cpes),
    url(r"^cves_CWE-\d+/$", views.cves),
    url(r"^cwes_CAPEC-\d+/$", views.capecs),
    url(r"^bdu_fstec/$", views.bdu_fstec),
    url(r"^search_bdu/$", views.search_bdu, name = 'search_bdu'),
    url(r"^bdu_fstec/BDU:\d+-\d+/$", views.bdu),
    url(r"^metasploit/$", views.metasploit),
    path('', views.sql, name='sql'),
    path('', views.home)


]
